"""add scheduled_date to orders

Revision ID: 1e44fe567c8a
Revises: 22be638ed857
Create Date: 2025-12-26 10:50:31.230210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e44fe567c8a'
down_revision: Union[str, Sequence[str], None] = '22be638ed857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('scheduled_date', sa.Date(), nullable=False))
    op.create_index(op.f('ix_orders_scheduled_date'), 'orders', ['scheduled_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_scheduled_date'), table_name='orders')
    op.drop_column('orders', 'scheduled_date')
    # ### end Alembic commands ###
