"""add unit_of_measure to products

Revision ID: 672a0e9b4aa4
Revises: 8fd3ce6d4c40
Create Date: 2025-12-26 11:18:04.919342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672a0e9b4aa4'
down_revision: Union[str, Sequence[str], None] = '8fd3ce6d4c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit_of_measure_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_products_unit_of_measure_id'), 'products', ['unit_of_measure_id'], unique=False)
    op.create_foreign_key(None, 'products', 'units_of_measure', ['unit_of_measure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_unit_of_measure_id'), table_name='products')
    op.drop_column('products', 'unit_of_measure_id')
    # ### end Alembic commands ###
