"""empty message

Revision ID: 71a2ca0f8aec
Revises: b98d28fc159d
Create Date: 2025-12-27 20:52:37.285733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a2ca0f8aec'
down_revision: Union[str, Sequence[str], None] = 'b98d28fc159d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False, comment='Snapshot completo do dashboard'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_snapshots_generated_at'), 'dashboard_snapshots', ['generated_at'], unique=False)
    op.create_table('order_item_breaks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('confirmed_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('difference_quantity', sa.Numeric(precision=12, scale=3), nullable=False, comment='expected_quantity - confirmed_quantity'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_breaks_order_id'), 'order_item_breaks', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_item_breaks_order_item_id'), 'order_item_breaks', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_item_breaks_order_item_id'), table_name='order_item_breaks')
    op.drop_index(op.f('ix_order_item_breaks_order_id'), table_name='order_item_breaks')
    op.drop_table('order_item_breaks')
    op.drop_index(op.f('ix_dashboard_snapshots_generated_at'), table_name='dashboard_snapshots')
    op.drop_table('dashboard_snapshots')
    # ### end Alembic commands ###
