"""empty message

Revision ID: b98d28fc159d
Revises: e7c708384077
Create Date: 2025-12-26 13:36:41.362195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98d28fc159d'
down_revision: Union[str, Sequence[str], None] = 'e7c708384077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('work_orders_order_id_key'), 'work_orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('work_orders_order_id_key'), 'work_orders', ['order_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
