"""empty message

Revision ID: e7c708384077
Revises: 672a0e9b4aa4
Create Date: 2025-12-26 12:55:53.989635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c708384077'
down_revision: Union[str, Sequence[str], None] = '672a0e9b4aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('produced_quantity', sa.Float(), nullable=True, comment='Real produced quantity informed by producer'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'produced_quantity')
    # ### end Alembic commands ###
